name: Badminton Checker Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

# Povoleni pro zapis do repozitare (nutne pro git-auto-commit-action)
permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Nastaveni tokenu je nutne, aby mohl commit spustit dalsi procesy (pokud nejake mas)
          # a aby mel spravna prava k zapisu.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          WA_PHONE: ${{ secrets.WA_PHONE }}
          WA_API_KEY: ${{ secrets.WA_API_KEY }}
          WA_PHONE_2: ${{ secrets.WA_PHONE_2 }}
          WA_API_KEY_2: ${{ secrets.WA_API_KEY_2 }}
        run: python init.py

      - name: Ulozit zmeny zpet do repozitare
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Aktualizace reportu bota (last_report.txt)"
          file_pattern: 'last_report.txt'
