name: Badminton Checker Bot

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: last_report.txt
          key: badminton-report-${{ github.run_id }}
          restore-keys: |
            badminton-report-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          WA_PHONE: ${{ secrets.WA_PHONE }}
          WA_API_KEY: ${{ secrets.WA_API_KEY }}
          WA_PHONE_2: ${{ secrets.WA_PHONE_2 }}
          WA_API_KEY_2: ${{ secrets.WA_API_KEY_2 }}
        run: python init.py

      - name: Save cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: last_report.txt
          key: badminton-report-${{ github.run_id }}